    
- name: Run docker-compose with letsencrypt service
  docker_compose:
    project_src: /root/sormas-docker
    pull: yes
    services:
      - postgres
      - sormas
      - pg_dump
      - letsencrypt
  retries: 2

- name: Check fullchain.pem exists.
  stat:
    path: /var/lib/docker/letsencrypt-config/nginx/dhparams.pem
  register: fullchain_details

- name: Copy pem files into correct folder
  copy:
    src: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ item }}.pem'
    dest: '/var/lib/docker/letsencrypt-config/etc/letsencrypt/live/{{ domain_name }}/{{ item }}.pem'
    remote_src: yes
  with_items:
    - fullchain
    - privkey
  when: fullchain_details.stat.exists and (use_existing_certs or selfsigned_cert_generation)