    
- name: Run docker-compose with letsencrypt service
  docker_compose:
    project_src: /root/sormas-docker
    pull: yes
    services:
      - postgres
      - sormas
#      - pg_dump
      - letsencrypt

- name: Check fullchain.pem exists.
  stat:
    path: /var/lib/docker/letsencrypt-config/nginx/dhparams.pem
  register: fullchain_details       

- name: Copy pem files into correct folder
  copy:
    src: '/var/lib/docker/letsencrypt-config/keys/letsecrypt/{{ item }}.pem'
    dest: '/var/lib/docker/letsencrypt-config/keys/letsecrypt/{{ domain_name }}/{{ item }}.pem'
    remote_src: yes
  with_items:
    - fullchain
    - privkey
  when: fullchain_details.exists

- name: Copy host.conf.j2 to LetsEncrypt volume
  template:
    src: host.conf.j2
    dest: '/var/lib/docker/letsencrypt-config/nginx/proxy-confs/{{ domain_name }}.conf'

- name: Include new config to default config
  lineinfile:
    path: '/var/lib/docker/letsencrypt-config/nginx/site-confs/default'
    regexp: '^include /config/nginx/proxy-confs/'
    line: 'include /config/nginx/proxy-confs/{{ domain_name }}.conf;'

- name: Restart letsencrypt service to apply changes
  docker_compose:
    project_src: /root/sormas-docker
    services: letsencrypt
    state: present
    restarted: yes

- name: Check dhparams.pem exists.
  stat:
    path: /var/lib/docker/letsencrypt-config/nginx/dhparams.pem
  register: file_details  

- name: Create pem file
  shell: docker-compose exec letsencrypt /bin/sh -c "openssl dhparam -out /config/nginx/dhparams.pem 2048"
  args:
    chdir: /root/sormas-docker
  when: selfsigned_cert_generation and not use_letsencrypt and not file_details.exists