---
- hosts: sormas
  become: yes
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Fix problem , that pip3 won't be installed on ubuntu servers
      apt:
        name: python3-pip
        state: present
      when: ansible_distribution == 'Ubuntu'
      
    - name: Execute geerlingguy.epel
      include_role:
        name: geerlingguy.repo-epel     
      when: ansible_os_family == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      
    - name: Execute geerlingguy.pip
      include_role:
        name: geerlingguy.pip      
    
    - name: Execute geerlingguy.docker
      include_role:
        name: geerlingguy.docker

    - name: Execute sormas-installation
      include_role:
        name: sormas-installation
