---
- hosts: sormas
  become: yes
  vars_files:
    - vars/vars.yml
    
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - sormas-installation    
    - { role: "letsencrypt", when: use_letsencrypt and not selfsigned_cert_generation }    
    - sormas-start