---
- hosts: sormas
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - { role: "letsencrypt", when: use_letsencrypt }
    - sormas-installation    
