- name: Insert letsencrypt configuration block docker-compose.yml
  blockinfile:
    path: /root/sormas-docker/docker-compose.yml
    block: |2
        letsencrypt:
          image: docker.netzlink.com/public/letsencrypt:v0.2
          container_name: letsencrypt
          environment:
            - PUID=1000
            - PGID=1000
            - TZ={{ timezone }}
            - URL={{ domain_name }}
            - VALIDATION=http
            - EMAIL={{ acme_email }}
            - DISABLE_CERTBOT={{ "true" if use_existing_certs else "true" if selfsigned_cert_generation else "false" if use_letsencrypt }}
          volumes:
            - /var/lib/docker/letsencrypt-config:/config
          ports:
            - 443:443
            - 80:80
          restart: unless-stopped

- name: Create letsencrypt directories to copy certificates
  file:
    path: '{{ item }}'
    state: directory
  when: selfsigned_cert_generation or use_existing_certs
  with_items:
    - '/var/lib/docker/letsencrypt-config/keys/letsencrypt'
    - '/var/lib/docker/letsencrypt-config/etc/letsencrypt/live/{{ domain_name }}'

- name: Copy existing pem files into letsencrypt folder
  copy:
    src: '{{ item }}.pem'
    dest: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ item }}.pem'
  with_items:
    - fullchain
    - privkey
  when: use_existing_certs

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
  when: selfsigned_cert_generation
  retries: 2

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ domain_name }}.csr'
    privatekey_path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
    common_name: '{{ domain_name }}'
  when: selfsigned_cert_generation
  
- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/fullchain.pem'
    privatekey_path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
    csr_path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ domain_name }}.csr'
    provider: selfsigned
  when: selfsigned_cert_generation
