- name: Remove port mapping for apache2
  lineinfile:
    path: /root/sormas-docker/docker-compose.yml
    regexp: '"{{ item }}:{{ item }}"'
    line: '      - {{ item }}'
  with_items:
    - 80
    - 443 

- name: Insert letsencrypt configuration block docker-compose.yml
  blockinfile:
    path: /root/sormas-docker/docker-compose.yml
    block: |2
        letsencrypt:
          image: linuxserver/letsencrypt
          container_name: letsencrypt
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - URL={{ domain_name }}
            - VALIDATION=http
            - EMAIL={{ acme_email }} #optional
            - DHLEVEL=2048 #optional
            - ONLY_SUBDOMAINS=false #optional
            - STAGING=false #optional
          volumes:
            - /var/lib/docker/letsencrypt-config:/config
          ports:
            - 443:443
            - 80:80
          restart: unless-stopped
