- name: Set hostname
  hostname:
    name: '{{ domain_name }}'

- name: Install git-core
  package:
    name: git-core
    state: present       

- name: Clone the Code repository to the remote host.
  git:
      repo: "https://github.com/hzi-braunschweig/SORMAS-Docker.git"
      dest: /root/sormas-docker
      version: "v1.37.2"
      force: yes

- name: Replace SORMAS_SERVER_URL in .env with correct domain
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^SORMAS_SERVER_URL='
    line: 'SORMAS_SERVER_URL={{ domain_name }}'
  
- name: Replace SORMAS_PATH in .env with correct domain
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^SORMAS_PATH='
    line: 'SORMAS_PATH=/var/lib/docker'
  
- name: Replace LATITUDE in .env with correct latitude
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^LATITUDE='
    line: 'LATITUDE={{ latitude }}'
  
- name: Replace LONGITUDE in .env with correct longitude
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^LONGITUDE='
    line: 'LONGITUDE={{ longitude }}'

- name: Replace TZ in .env with correct timezone
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^TZ='
    line: 'TZ={{ timezone }}'

