- name: Set hostname
  hostname:
    name: '{{ domain_name }}'

- name: Install git-core
  package:
    name: git-core
    state: present       

- name: Clone the Code repository to the remote host.
  git:
      repo: "https://github.com/hzi-braunschweig/SORMAS-Docker.git"
      dest: /root/sormas-docker
      version: "{{ sormas_version }}"
      force: yes

- name: Replace SORMAS_SERVER_URL in .env with correct domain
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^SORMAS_SERVER_URL='
    line: 'SORMAS_SERVER_URL={{ domain_name }}'
  
- name: Replace SORMAS_PATH in .env with correct domain
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^SORMAS_PATH='
    line: 'SORMAS_PATH=/var/lib/docker'
  
- name: Replace LATITUDE in .env with correct latitude
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^LATITUDE='
    line: 'LATITUDE={{ latitude }}'
  
- name: Replace LONGITUDE in .env with correct longitude
  lineinfile:
    path: /root/sormas-docker/.env
    regexp: '^LONGITUDE='
    line: 'LONGITUDE={{ longitude }}'

- name: Create letsencrypt directory to copy certificates
  file:
    path: /var/lib/docker/letsencrypt-config/keys/letsencrypt
    state: directory    

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
    select_crypto_backend: cryptography
  when: selfsigned_cert_generation and not use_letsencrypt

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ domain_name }}.csr'
    privatekey_path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
    common_name: '{{ domain_name }}'
  when: selfsigned_cert_generation and not use_letsencrypt
  
- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: '/root/sormas-docker/apache2/certs/fullchaim.pem'
    privatekey_path: '/var/lib/docker/letsencrypt-config/keys/letsencrypt/privkey.pem'
    csr_path: /var/lib/docker/letsencrypt-config/keys/letsencrypt/{{ domain_name }}.csr'
    provider: selfsigned
  when: selfsigned_cert_generation and not use_letsencrypt